/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_syntax = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_in = 5,
  anon_sym_COLON_COLON_EQ = 6,
  anon_sym_COMMA = 7,
  anon_sym_PIPE = 8,
  anon_sym_rules = 9,
  anon_sym_rule = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_EQ_GT = 13,
  anon_sym_transition = 14,
  anon_sym_TILDE_GT = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_EQ = 18,
  anon_sym_SLASH_EQ = 19,
  anon_sym_PERCENTtest_COLON = 20,
  sym_regular_comment = 21,
  sym_identifier = 22,
  sym_string = 23,
  sym_source_file = 24,
  sym_declaration = 25,
  sym_syntax_block = 26,
  sym_syntax_rule = 27,
  sym_variable_list = 28,
  sym_production_list = 29,
  sym_rules_block = 30,
  sym_rule = 31,
  sym_term_list = 32,
  sym_transition_declaration = 33,
  sym_rewrite_rule = 34,
  sym_term = 35,
  sym_primary_term = 36,
  sym_atom = 37,
  sym_functor = 38,
  sym_equality = 39,
  sym_inequality = 40,
  sym_transition_term = 41,
  sym_test_comment = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_syntax_block_repeat1 = 44,
  aux_sym_variable_list_repeat1 = 45,
  aux_sym_production_list_repeat1 = 46,
  aux_sym_rules_block_repeat1 = 47,
  aux_sym_term_list_repeat1 = 48,
  aux_sym_rewrite_rule_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_syntax] = "syntax",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_in] = "in",
  [anon_sym_COLON_COLON_EQ] = "::=",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE] = "|",
  [anon_sym_rules] = "rules",
  [anon_sym_rule] = "rule",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_transition] = "transition",
  [anon_sym_TILDE_GT] = "~>",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_PERCENTtest_COLON] = "%test:",
  [sym_regular_comment] = "regular_comment",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_syntax_block] = "syntax_block",
  [sym_syntax_rule] = "syntax_rule",
  [sym_variable_list] = "variable_list",
  [sym_production_list] = "production_list",
  [sym_rules_block] = "rules_block",
  [sym_rule] = "rule",
  [sym_term_list] = "term_list",
  [sym_transition_declaration] = "transition_declaration",
  [sym_rewrite_rule] = "rewrite_rule",
  [sym_term] = "term",
  [sym_primary_term] = "primary_term",
  [sym_atom] = "atom",
  [sym_functor] = "functor",
  [sym_equality] = "equality",
  [sym_inequality] = "inequality",
  [sym_transition_term] = "transition_term",
  [sym_test_comment] = "test_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_syntax_block_repeat1] = "syntax_block_repeat1",
  [aux_sym_variable_list_repeat1] = "variable_list_repeat1",
  [aux_sym_production_list_repeat1] = "production_list_repeat1",
  [aux_sym_rules_block_repeat1] = "rules_block_repeat1",
  [aux_sym_term_list_repeat1] = "term_list_repeat1",
  [aux_sym_rewrite_rule_repeat1] = "rewrite_rule_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_syntax] = anon_sym_syntax,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_COLON_COLON_EQ] = anon_sym_COLON_COLON_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_rules] = anon_sym_rules,
  [anon_sym_rule] = anon_sym_rule,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_transition] = anon_sym_transition,
  [anon_sym_TILDE_GT] = anon_sym_TILDE_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_PERCENTtest_COLON] = anon_sym_PERCENTtest_COLON,
  [sym_regular_comment] = sym_regular_comment,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_syntax_block] = sym_syntax_block,
  [sym_syntax_rule] = sym_syntax_rule,
  [sym_variable_list] = sym_variable_list,
  [sym_production_list] = sym_production_list,
  [sym_rules_block] = sym_rules_block,
  [sym_rule] = sym_rule,
  [sym_term_list] = sym_term_list,
  [sym_transition_declaration] = sym_transition_declaration,
  [sym_rewrite_rule] = sym_rewrite_rule,
  [sym_term] = sym_term,
  [sym_primary_term] = sym_primary_term,
  [sym_atom] = sym_atom,
  [sym_functor] = sym_functor,
  [sym_equality] = sym_equality,
  [sym_inequality] = sym_inequality,
  [sym_transition_term] = sym_transition_term,
  [sym_test_comment] = sym_test_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_syntax_block_repeat1] = aux_sym_syntax_block_repeat1,
  [aux_sym_variable_list_repeat1] = aux_sym_variable_list_repeat1,
  [aux_sym_production_list_repeat1] = aux_sym_production_list_repeat1,
  [aux_sym_rules_block_repeat1] = aux_sym_rules_block_repeat1,
  [aux_sym_term_list_repeat1] = aux_sym_term_list_repeat1,
  [aux_sym_rewrite_rule_repeat1] = aux_sym_rewrite_rule_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_syntax] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rules] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_transition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTtest_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_regular_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_syntax_block] = {
    .visible = true,
    .named = true,
  },
  [sym_syntax_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_list] = {
    .visible = true,
    .named = true,
  },
  [sym_production_list] = {
    .visible = true,
    .named = true,
  },
  [sym_rules_block] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_term_list] = {
    .visible = true,
    .named = true,
  },
  [sym_transition_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_rewrite_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_functor] = {
    .visible = true,
    .named = true,
  },
  [sym_equality] = {
    .visible = true,
    .named = true,
  },
  [sym_inequality] = {
    .visible = true,
    .named = true,
  },
  [sym_transition_term] = {
    .visible = true,
    .named = true,
  },
  [sym_test_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_syntax_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_production_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rules_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rewrite_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 4,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 18,
  [27] = 8,
  [28] = 10,
  [29] = 29,
  [30] = 29,
  [31] = 19,
  [32] = 13,
  [33] = 33,
  [34] = 15,
  [35] = 17,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 36,
  [43] = 43,
  [44] = 37,
  [45] = 45,
  [46] = 46,
  [47] = 38,
  [48] = 39,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 61,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 1,
        '%', 61,
        '(', 52,
        ')', 53,
        ',', 40,
        '/', 4,
        ':', 3,
        ';', 33,
        '=', 55,
        '[', 46,
        ']', 47,
        'i', 16,
        'r', 25,
        's', 28,
        't', 21,
        '{', 36,
        '|', 41,
        '}', 37,
        '~', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(83);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(63);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == '}') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(56);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(48);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(51);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 27:
      if (lookahead == 'x') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 1,
        '%', 63,
        '(', 52,
        ')', 53,
        ',', 40,
        '/', 4,
        ':', 3,
        ';', 33,
        '=', 54,
        '[', 46,
        ']', 47,
        '{', 36,
        '|', 41,
        '}', 37,
        '~', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '%', 61,
        '(', 52,
        '/', 4,
        '=', 54,
        'r', 79,
        's', 81,
        't', 74,
        '~', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_syntax);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_syntax);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON_COLON_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_rules);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_rules);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_rule);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_rule);
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_transition);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_transition);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_TILDE_GT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(48);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_PERCENTtest_COLON);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == ':') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 's') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 't') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 't') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 31},
  [2] = {.lex_state = 31},
  [3] = {.lex_state = 31},
  [4] = {.lex_state = 31},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 31},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 31},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 31},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 31},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 30},
  [25] = {.lex_state = 30},
  [26] = {.lex_state = 30},
  [27] = {.lex_state = 30},
  [28] = {.lex_state = 30},
  [29] = {.lex_state = 30},
  [30] = {.lex_state = 30},
  [31] = {.lex_state = 30},
  [32] = {.lex_state = 30},
  [33] = {.lex_state = 30},
  [34] = {.lex_state = 30},
  [35] = {.lex_state = 30},
  [36] = {.lex_state = 31},
  [37] = {.lex_state = 31},
  [38] = {.lex_state = 31},
  [39] = {.lex_state = 31},
  [40] = {.lex_state = 31},
  [41] = {.lex_state = 31},
  [42] = {.lex_state = 30},
  [43] = {.lex_state = 30},
  [44] = {.lex_state = 30},
  [45] = {.lex_state = 30},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 30},
  [48] = {.lex_state = 30},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 30},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 30},
  [55] = {.lex_state = 30},
  [56] = {.lex_state = 30},
  [57] = {.lex_state = 30},
  [58] = {.lex_state = 30},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 30},
  [62] = {.lex_state = 30},
  [63] = {.lex_state = 30},
  [64] = {.lex_state = 30},
  [65] = {.lex_state = 30},
  [66] = {.lex_state = 30},
  [67] = {.lex_state = 30},
  [68] = {.lex_state = 30},
  [69] = {.lex_state = 30},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 30},
  [72] = {.lex_state = 30},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 30},
  [75] = {.lex_state = 30},
  [76] = {.lex_state = 30},
  [77] = {.lex_state = 30},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 30},
  [80] = {.lex_state = 30},
  [81] = {.lex_state = 30},
  [82] = {.lex_state = 30},
  [83] = {.lex_state = 30},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 30},
  [86] = {.lex_state = 30},
  [87] = {.lex_state = 30},
  [88] = {.lex_state = 30},
  [89] = {.lex_state = 30},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 30},
  [92] = {.lex_state = 30},
  [93] = {.lex_state = 30},
  [94] = {.lex_state = 30},
  [95] = {.lex_state = 30},
  [96] = {.lex_state = 30},
  [97] = {.lex_state = 30},
  [98] = {.lex_state = 30},
  [99] = {.lex_state = 30},
  [100] = {.lex_state = 30},
  [101] = {.lex_state = 30},
  [102] = {.lex_state = 30},
  [103] = {.lex_state = 30},
  [104] = {.lex_state = 30},
  [105] = {.lex_state = 30},
  [106] = {.lex_state = 30},
  [107] = {.lex_state = 30},
  [108] = {.lex_state = 30},
  [109] = {.lex_state = 30},
  [110] = {.lex_state = 30},
  [111] = {.lex_state = 30},
  [112] = {.lex_state = 30},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_syntax] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_COLON_COLON_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_rules] = ACTIONS(1),
    [anon_sym_rule] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_transition] = ACTIONS(1),
    [anon_sym_TILDE_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_PERCENTtest_COLON] = ACTIONS(1),
    [sym_regular_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(87),
    [sym_declaration] = STATE(97),
    [sym_syntax_block] = STATE(100),
    [sym_rules_block] = STATE(100),
    [sym_transition_declaration] = STATE(100),
    [sym_rewrite_rule] = STATE(100),
    [sym_test_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_syntax] = ACTIONS(7),
    [anon_sym_rules] = ACTIONS(9),
    [anon_sym_transition] = ACTIONS(11),
    [anon_sym_PERCENTtest_COLON] = ACTIONS(13),
    [sym_regular_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(7), 1,
      anon_sym_syntax,
    ACTIONS(9), 1,
      anon_sym_rules,
    ACTIONS(11), 1,
      anon_sym_transition,
    ACTIONS(13), 1,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(97), 1,
      sym_declaration,
    STATE(3), 2,
      sym_test_comment,
      aux_sym_source_file_repeat1,
    STATE(100), 4,
      sym_syntax_block,
      sym_rules_block,
      sym_transition_declaration,
      sym_rewrite_rule,
  [35] = 10,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_syntax,
    ACTIONS(24), 1,
      anon_sym_rules,
    ACTIONS(27), 1,
      anon_sym_transition,
    ACTIONS(30), 1,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(33), 1,
      sym_identifier,
    STATE(97), 1,
      sym_declaration,
    STATE(3), 2,
      sym_test_comment,
      aux_sym_source_file_repeat1,
    STATE(100), 4,
      sym_syntax_block,
      sym_rules_block,
      sym_transition_declaration,
      sym_rewrite_rule,
  [70] = 4,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(40), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(36), 5,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
  [90] = 8,
    ACTIONS(42), 1,
      anon_sym_RBRACK,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(63), 1,
      sym_term,
    STATE(79), 1,
      sym_term_list,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [118] = 8,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_primary_term,
    STATE(63), 1,
      sym_term,
    STATE(94), 1,
      sym_term_list,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [146] = 8,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(50), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_primary_term,
    STATE(63), 1,
      sym_term,
    STATE(112), 1,
      sym_term_list,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [174] = 6,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(56), 1,
      anon_sym_TILDE_GT,
    ACTIONS(58), 1,
      anon_sym_EQ,
    ACTIONS(60), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(54), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [197] = 7,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_primary_term,
    STATE(66), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [222] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(66), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
  [239] = 7,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_primary_term,
    STATE(52), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [264] = 7,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(70), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_primary_term,
    STATE(64), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [289] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(74), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
  [306] = 7,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(65), 1,
      sym_term,
    STATE(91), 1,
      sym_production_list,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [331] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(78), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
  [348] = 3,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(36), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [365] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(84), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
  [382] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(48), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [404] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(86), 1,
      sym_identifier,
    STATE(8), 1,
      sym_primary_term,
    STATE(38), 1,
      sym_term,
    STATE(10), 2,
      sym_atom,
      sym_functor,
    STATE(37), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [426] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(69), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [448] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(107), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [470] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(101), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [492] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(81), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [514] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(71), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [536] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(72), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [558] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(86), 1,
      sym_identifier,
    STATE(8), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_term,
    STATE(10), 2,
      sym_atom,
      sym_functor,
    STATE(37), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [580] = 5,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(88), 1,
      anon_sym_TILDE_GT,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(52), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [600] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(64), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [614] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(86), 1,
      sym_identifier,
    STATE(8), 1,
      sym_primary_term,
    STATE(36), 1,
      sym_term,
    STATE(10), 2,
      sym_atom,
      sym_functor,
    STATE(37), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [636] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(42), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [658] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(27), 1,
      sym_primary_term,
    STATE(47), 1,
      sym_term,
    STATE(28), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [680] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(72), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [694] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(86), 1,
      sym_identifier,
    STATE(8), 1,
      sym_primary_term,
    STATE(40), 1,
      sym_term,
    STATE(10), 2,
      sym_atom,
      sym_functor,
    STATE(37), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [716] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(76), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [730] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(82), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [744] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(94), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(96), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [758] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(54), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [772] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(100), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [786] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(104), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [800] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(108), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [814] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(110), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [828] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(94), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [839] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(45), 1,
      aux_sym_syntax_block_repeat1,
    STATE(82), 1,
      sym_syntax_rule,
    STATE(84), 1,
      sym_variable_list,
  [858] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(52), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [869] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_syntax_block_repeat1,
    STATE(82), 1,
      sym_syntax_rule,
    STATE(84), 1,
      sym_variable_list,
  [888] = 6,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(120), 1,
      sym_identifier,
    STATE(46), 1,
      aux_sym_syntax_block_repeat1,
    STATE(82), 1,
      sym_syntax_rule,
    STATE(84), 1,
      sym_variable_list,
  [907] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(98), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [918] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(102), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [929] = 5,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    ACTIONS(125), 1,
      anon_sym_rule,
    STATE(50), 1,
      aux_sym_rules_block_repeat1,
    STATE(96), 1,
      sym_rule,
  [945] = 5,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 1,
      anon_sym_rule,
    STATE(50), 1,
      aux_sym_rules_block_repeat1,
    STATE(96), 1,
      sym_rule,
  [961] = 5,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(125), 1,
      anon_sym_rule,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      aux_sym_rules_block_repeat1,
    STATE(96), 1,
      sym_rule,
  [977] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_rewrite_rule_repeat1,
  [990] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(138), 1,
      anon_sym_in,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_variable_list_repeat1,
  [1003] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_rewrite_rule_repeat1,
  [1016] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(145), 1,
      anon_sym_SEMI,
    ACTIONS(147), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_term_list_repeat1,
  [1029] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(149), 1,
      anon_sym_SEMI,
    ACTIONS(152), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_term_list_repeat1,
  [1042] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(154), 1,
      anon_sym_SEMI,
    ACTIONS(156), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_production_list_repeat1,
  [1055] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    ACTIONS(161), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_production_list_repeat1,
  [1068] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(163), 1,
      anon_sym_in,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_variable_list_repeat1,
  [1081] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_in,
    STATE(59), 1,
      aux_sym_variable_list_repeat1,
  [1094] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_rewrite_rule_repeat1,
  [1107] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_rewrite_rule_repeat1,
  [1120] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(145), 1,
      anon_sym_SEMI,
    ACTIONS(176), 1,
      anon_sym_RBRACK,
    STATE(55), 1,
      aux_sym_term_list_repeat1,
  [1133] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_rewrite_rule_repeat1,
  [1146] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(161), 1,
      anon_sym_PIPE,
    ACTIONS(180), 1,
      anon_sym_SEMI,
    STATE(58), 1,
      aux_sym_production_list_repeat1,
  [1159] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_rewrite_rule_repeat1,
  [1172] = 4,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_rewrite_rule_repeat1,
  [1185] = 3,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(186), 1,
      anon_sym_SEMI,
    ACTIONS(188), 1,
      anon_sym_COLON_COLON_EQ,
  [1195] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(174), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1203] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(127), 2,
      anon_sym_RBRACE,
      anon_sym_rule,
  [1211] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(152), 2,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1219] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(154), 2,
      anon_sym_SEMI,
      anon_sym_PIPE,
  [1227] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(138), 2,
      anon_sym_in,
      anon_sym_COMMA,
  [1235] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(118), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1243] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(190), 1,
      anon_sym_SEMI,
  [1250] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(192), 1,
      anon_sym_LBRACK,
  [1257] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
  [1264] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(196), 1,
      anon_sym_EQ_GT,
  [1271] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
  [1278] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(200), 1,
      anon_sym_SEMI,
  [1285] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(202), 1,
      anon_sym_SEMI,
  [1292] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(204), 1,
      anon_sym_SEMI,
  [1299] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(206), 1,
      anon_sym_SEMI,
  [1306] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(208), 1,
      anon_sym_in,
  [1313] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(210), 1,
      anon_sym_LBRACK,
  [1320] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(212), 1,
      sym_identifier,
  [1327] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
  [1334] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [1341] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(218), 1,
      anon_sym_SEMI,
  [1348] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(220), 1,
      anon_sym_EQ_GT,
  [1355] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(222), 1,
      anon_sym_SEMI,
  [1362] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(224), 1,
      sym_string,
  [1369] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(226), 1,
      anon_sym_SEMI,
  [1376] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
  [1383] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(230), 1,
      anon_sym_SEMI,
  [1390] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(232), 1,
      anon_sym_SEMI,
  [1397] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(234), 1,
      anon_sym_SEMI,
  [1404] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(236), 1,
      sym_identifier,
  [1411] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(238), 1,
      anon_sym_EQ,
  [1418] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(240), 1,
      anon_sym_SEMI,
  [1425] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(242), 1,
      anon_sym_SEMI,
  [1432] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
  [1439] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(246), 1,
      sym_identifier,
  [1446] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
  [1453] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(250), 1,
      anon_sym_EQ,
  [1460] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(252), 1,
      anon_sym_TILDE_GT,
  [1467] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(254), 1,
      anon_sym_SEMI,
  [1474] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(256), 1,
      anon_sym_LPAREN,
  [1481] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(258), 1,
      sym_identifier,
  [1488] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(260), 1,
      anon_sym_EQ,
  [1495] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(262), 1,
      anon_sym_SEMI,
  [1502] = 2,
    ACTIONS(44), 1,
      sym_regular_comment,
    ACTIONS(48), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 118,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 197,
  [SMALL_STATE(10)] = 222,
  [SMALL_STATE(11)] = 239,
  [SMALL_STATE(12)] = 264,
  [SMALL_STATE(13)] = 289,
  [SMALL_STATE(14)] = 306,
  [SMALL_STATE(15)] = 331,
  [SMALL_STATE(16)] = 348,
  [SMALL_STATE(17)] = 365,
  [SMALL_STATE(18)] = 382,
  [SMALL_STATE(19)] = 404,
  [SMALL_STATE(20)] = 426,
  [SMALL_STATE(21)] = 448,
  [SMALL_STATE(22)] = 470,
  [SMALL_STATE(23)] = 492,
  [SMALL_STATE(24)] = 514,
  [SMALL_STATE(25)] = 536,
  [SMALL_STATE(26)] = 558,
  [SMALL_STATE(27)] = 580,
  [SMALL_STATE(28)] = 600,
  [SMALL_STATE(29)] = 614,
  [SMALL_STATE(30)] = 636,
  [SMALL_STATE(31)] = 658,
  [SMALL_STATE(32)] = 680,
  [SMALL_STATE(33)] = 694,
  [SMALL_STATE(34)] = 716,
  [SMALL_STATE(35)] = 730,
  [SMALL_STATE(36)] = 744,
  [SMALL_STATE(37)] = 758,
  [SMALL_STATE(38)] = 772,
  [SMALL_STATE(39)] = 786,
  [SMALL_STATE(40)] = 800,
  [SMALL_STATE(41)] = 814,
  [SMALL_STATE(42)] = 828,
  [SMALL_STATE(43)] = 839,
  [SMALL_STATE(44)] = 858,
  [SMALL_STATE(45)] = 869,
  [SMALL_STATE(46)] = 888,
  [SMALL_STATE(47)] = 907,
  [SMALL_STATE(48)] = 918,
  [SMALL_STATE(49)] = 929,
  [SMALL_STATE(50)] = 945,
  [SMALL_STATE(51)] = 961,
  [SMALL_STATE(52)] = 977,
  [SMALL_STATE(53)] = 990,
  [SMALL_STATE(54)] = 1003,
  [SMALL_STATE(55)] = 1016,
  [SMALL_STATE(56)] = 1029,
  [SMALL_STATE(57)] = 1042,
  [SMALL_STATE(58)] = 1055,
  [SMALL_STATE(59)] = 1068,
  [SMALL_STATE(60)] = 1081,
  [SMALL_STATE(61)] = 1094,
  [SMALL_STATE(62)] = 1107,
  [SMALL_STATE(63)] = 1120,
  [SMALL_STATE(64)] = 1133,
  [SMALL_STATE(65)] = 1146,
  [SMALL_STATE(66)] = 1159,
  [SMALL_STATE(67)] = 1172,
  [SMALL_STATE(68)] = 1185,
  [SMALL_STATE(69)] = 1195,
  [SMALL_STATE(70)] = 1203,
  [SMALL_STATE(71)] = 1211,
  [SMALL_STATE(72)] = 1219,
  [SMALL_STATE(73)] = 1227,
  [SMALL_STATE(74)] = 1235,
  [SMALL_STATE(75)] = 1243,
  [SMALL_STATE(76)] = 1250,
  [SMALL_STATE(77)] = 1257,
  [SMALL_STATE(78)] = 1264,
  [SMALL_STATE(79)] = 1271,
  [SMALL_STATE(80)] = 1278,
  [SMALL_STATE(81)] = 1285,
  [SMALL_STATE(82)] = 1292,
  [SMALL_STATE(83)] = 1299,
  [SMALL_STATE(84)] = 1306,
  [SMALL_STATE(85)] = 1313,
  [SMALL_STATE(86)] = 1320,
  [SMALL_STATE(87)] = 1327,
  [SMALL_STATE(88)] = 1334,
  [SMALL_STATE(89)] = 1341,
  [SMALL_STATE(90)] = 1348,
  [SMALL_STATE(91)] = 1355,
  [SMALL_STATE(92)] = 1362,
  [SMALL_STATE(93)] = 1369,
  [SMALL_STATE(94)] = 1376,
  [SMALL_STATE(95)] = 1383,
  [SMALL_STATE(96)] = 1390,
  [SMALL_STATE(97)] = 1397,
  [SMALL_STATE(98)] = 1404,
  [SMALL_STATE(99)] = 1411,
  [SMALL_STATE(100)] = 1418,
  [SMALL_STATE(101)] = 1425,
  [SMALL_STATE(102)] = 1432,
  [SMALL_STATE(103)] = 1439,
  [SMALL_STATE(104)] = 1446,
  [SMALL_STATE(105)] = 1453,
  [SMALL_STATE(106)] = 1460,
  [SMALL_STATE(107)] = 1467,
  [SMALL_STATE(108)] = 1474,
  [SMALL_STATE(109)] = 1481,
  [SMALL_STATE(110)] = 1488,
  [SMALL_STATE(111)] = 1495,
  [SMALL_STATE(112)] = 1502,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_term, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_term, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functor, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functor, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functor, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functor, 4, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functor, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functor, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equality, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inequality, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inequality, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transition_term, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transition_term, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_comment, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_test_comment, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_syntax_block_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_syntax_block_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rules_block_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rules_block_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_list, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_list_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_list_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_production_list_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_production_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production_list, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rewrite_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rewrite_rule_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_list, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production_list, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_rule, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 7, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rules_block, 4, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_rule, 7, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transition_declaration, 4, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [214] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_block, 4, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rules_block, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_rule, 5, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 8, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 9, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_rule, 6, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_rule, 5, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_block, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_analysislang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "analysislang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
