/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 128
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_syntax = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_in = 5,
  anon_sym_COLON_COLON_EQ = 6,
  anon_sym_alias = 7,
  anon_sym_as = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_PIPE = 12,
  anon_sym_rules = 13,
  anon_sym_rule = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  anon_sym_EQ_GT = 17,
  anon_sym_transition = 18,
  anon_sym_TILDE_GT = 19,
  anon_sym_EQ = 20,
  anon_sym_SLASH_EQ = 21,
  anon_sym_PERCENTtest_COLON = 22,
  sym_regular_comment = 23,
  sym_haskell_expression = 24,
  sym_haskell_block = 25,
  sym_integer_literal = 26,
  sym_identifier = 27,
  sym_string = 28,
  sym_source_file = 29,
  sym_declaration = 30,
  sym_syntax_block = 31,
  sym_syntax_rule = 32,
  sym_type_alias = 33,
  sym_type_ref = 34,
  sym_type_name = 35,
  sym_variable_list = 36,
  sym_production_list = 37,
  sym_rules_block = 38,
  sym_rule = 39,
  sym_term_list = 40,
  sym_transition_declaration = 41,
  sym_rewrite_rule = 42,
  sym_term = 43,
  sym_primary_term = 44,
  sym_atom = 45,
  sym_functor = 46,
  sym_equality = 47,
  sym_inequality = 48,
  sym_transition_term = 49,
  sym_test_comment = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_syntax_block_repeat1 = 52,
  aux_sym_type_ref_repeat1 = 53,
  aux_sym_variable_list_repeat1 = 54,
  aux_sym_production_list_repeat1 = 55,
  aux_sym_rules_block_repeat1 = 56,
  aux_sym_term_list_repeat1 = 57,
  aux_sym_rewrite_rule_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_syntax] = "syntax",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_in] = "in",
  [anon_sym_COLON_COLON_EQ] = "::=",
  [anon_sym_alias] = "alias",
  [anon_sym_as] = "as",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PIPE] = "|",
  [anon_sym_rules] = "rules",
  [anon_sym_rule] = "rule",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_transition] = "transition",
  [anon_sym_TILDE_GT] = "~>",
  [anon_sym_EQ] = "=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_PERCENTtest_COLON] = "%test:",
  [sym_regular_comment] = "regular_comment",
  [sym_haskell_expression] = "haskell_expression",
  [sym_haskell_block] = "haskell_block",
  [sym_integer_literal] = "integer_literal",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_syntax_block] = "syntax_block",
  [sym_syntax_rule] = "syntax_rule",
  [sym_type_alias] = "type_alias",
  [sym_type_ref] = "type_ref",
  [sym_type_name] = "type_name",
  [sym_variable_list] = "variable_list",
  [sym_production_list] = "production_list",
  [sym_rules_block] = "rules_block",
  [sym_rule] = "rule",
  [sym_term_list] = "term_list",
  [sym_transition_declaration] = "transition_declaration",
  [sym_rewrite_rule] = "rewrite_rule",
  [sym_term] = "term",
  [sym_primary_term] = "primary_term",
  [sym_atom] = "atom",
  [sym_functor] = "functor",
  [sym_equality] = "equality",
  [sym_inequality] = "inequality",
  [sym_transition_term] = "transition_term",
  [sym_test_comment] = "test_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_syntax_block_repeat1] = "syntax_block_repeat1",
  [aux_sym_type_ref_repeat1] = "type_ref_repeat1",
  [aux_sym_variable_list_repeat1] = "variable_list_repeat1",
  [aux_sym_production_list_repeat1] = "production_list_repeat1",
  [aux_sym_rules_block_repeat1] = "rules_block_repeat1",
  [aux_sym_term_list_repeat1] = "term_list_repeat1",
  [aux_sym_rewrite_rule_repeat1] = "rewrite_rule_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_syntax] = anon_sym_syntax,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_COLON_COLON_EQ] = anon_sym_COLON_COLON_EQ,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_rules] = anon_sym_rules,
  [anon_sym_rule] = anon_sym_rule,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_transition] = anon_sym_transition,
  [anon_sym_TILDE_GT] = anon_sym_TILDE_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_PERCENTtest_COLON] = anon_sym_PERCENTtest_COLON,
  [sym_regular_comment] = sym_regular_comment,
  [sym_haskell_expression] = sym_haskell_expression,
  [sym_haskell_block] = sym_haskell_block,
  [sym_integer_literal] = sym_integer_literal,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_syntax_block] = sym_syntax_block,
  [sym_syntax_rule] = sym_syntax_rule,
  [sym_type_alias] = sym_type_alias,
  [sym_type_ref] = sym_type_ref,
  [sym_type_name] = sym_type_name,
  [sym_variable_list] = sym_variable_list,
  [sym_production_list] = sym_production_list,
  [sym_rules_block] = sym_rules_block,
  [sym_rule] = sym_rule,
  [sym_term_list] = sym_term_list,
  [sym_transition_declaration] = sym_transition_declaration,
  [sym_rewrite_rule] = sym_rewrite_rule,
  [sym_term] = sym_term,
  [sym_primary_term] = sym_primary_term,
  [sym_atom] = sym_atom,
  [sym_functor] = sym_functor,
  [sym_equality] = sym_equality,
  [sym_inequality] = sym_inequality,
  [sym_transition_term] = sym_transition_term,
  [sym_test_comment] = sym_test_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_syntax_block_repeat1] = aux_sym_syntax_block_repeat1,
  [aux_sym_type_ref_repeat1] = aux_sym_type_ref_repeat1,
  [aux_sym_variable_list_repeat1] = aux_sym_variable_list_repeat1,
  [aux_sym_production_list_repeat1] = aux_sym_production_list_repeat1,
  [aux_sym_rules_block_repeat1] = aux_sym_rules_block_repeat1,
  [aux_sym_term_list_repeat1] = aux_sym_term_list_repeat1,
  [aux_sym_rewrite_rule_repeat1] = aux_sym_rewrite_rule_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_syntax] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rules] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_transition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTtest_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_regular_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_haskell_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_haskell_block] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_syntax_block] = {
    .visible = true,
    .named = true,
  },
  [sym_syntax_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_type_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_list] = {
    .visible = true,
    .named = true,
  },
  [sym_production_list] = {
    .visible = true,
    .named = true,
  },
  [sym_rules_block] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_term_list] = {
    .visible = true,
    .named = true,
  },
  [sym_transition_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_rewrite_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_functor] = {
    .visible = true,
    .named = true,
  },
  [sym_equality] = {
    .visible = true,
    .named = true,
  },
  [sym_inequality] = {
    .visible = true,
    .named = true,
  },
  [sym_transition_term] = {
    .visible = true,
    .named = true,
  },
  [sym_test_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_syntax_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_ref_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_production_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rules_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rewrite_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias_name = 1,
  field_original_type = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias_name] = "alias_name",
  [field_original_type] = "original_type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_alias_name, 3},
    {field_original_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 13,
  [28] = 15,
  [29] = 14,
  [30] = 11,
  [31] = 19,
  [32] = 26,
  [33] = 16,
  [34] = 20,
  [35] = 22,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 43,
  [48] = 38,
  [49] = 49,
  [50] = 44,
  [51] = 41,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 72,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '"', 1,
        '$', 35,
        '%', 78,
        '(', 57,
        ')', 59,
        ',', 58,
        '/', 5,
        ':', 4,
        ';', 46,
        '=', 72,
        '[', 65,
        ']', 66,
        'a', 17,
        'i', 20,
        'r', 31,
        's', 34,
        't', 25,
        '{', 50,
        '|', 60,
        '}', 51,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(107);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '%', 80,
        '(', 57,
        ')', 59,
        ',', 58,
        ':', 4,
        ';', 46,
        'a', 26,
        'i', 20,
        'r', 32,
        '}', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(80);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == 'a') ADVANCE(92);
      if (lookahead == '}') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(73);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(67);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(70);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(54);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 33:
      if (lookahead == 'x') ADVANCE(47);
      END_STATE();
    case 34:
      if (lookahead == 'y') ADVANCE(21);
      END_STATE();
    case 35:
      if (lookahead == '{') ADVANCE(38);
      END_STATE();
    case 36:
      if (lookahead == '{') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == '{') ADVANCE(36);
      END_STATE();
    case 38:
      if (lookahead == '}') ADVANCE(81);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      if (lookahead == '}') ADVANCE(82);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == '}') ADVANCE(39);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 41:
      if (lookahead == '}') ADVANCE(40);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 43:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '"', 1,
        '$', 35,
        '%', 80,
        '(', 57,
        ')', 59,
        ',', 58,
        '/', 5,
        ':', 4,
        ';', 46,
        '=', 71,
        '[', 65,
        ']', 66,
        '{', 49,
        '|', 60,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '%', 78,
        '(', 57,
        '/', 5,
        '=', 71,
        'r', 103,
        's', 105,
        't', 97,
        '{', 37,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_syntax);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_syntax);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(36);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON_COLON_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_alias);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_rules);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_rules);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_rule);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_rule);
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_transition);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_transition);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_TILDE_GT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(67);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_PERCENTtest_COLON);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == ':') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 's') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 't') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead == 't') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_regular_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_haskell_expression);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_haskell_block);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 44},
  [2] = {.lex_state = 44},
  [3] = {.lex_state = 44},
  [4] = {.lex_state = 43},
  [5] = {.lex_state = 43},
  [6] = {.lex_state = 43},
  [7] = {.lex_state = 43},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 43},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 44},
  [12] = {.lex_state = 43},
  [13] = {.lex_state = 43},
  [14] = {.lex_state = 43},
  [15] = {.lex_state = 43},
  [16] = {.lex_state = 44},
  [17] = {.lex_state = 43},
  [18] = {.lex_state = 43},
  [19] = {.lex_state = 44},
  [20] = {.lex_state = 44},
  [21] = {.lex_state = 43},
  [22] = {.lex_state = 44},
  [23] = {.lex_state = 43},
  [24] = {.lex_state = 43},
  [25] = {.lex_state = 43},
  [26] = {.lex_state = 44},
  [27] = {.lex_state = 43},
  [28] = {.lex_state = 43},
  [29] = {.lex_state = 43},
  [30] = {.lex_state = 43},
  [31] = {.lex_state = 43},
  [32] = {.lex_state = 43},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 43},
  [35] = {.lex_state = 43},
  [36] = {.lex_state = 44},
  [37] = {.lex_state = 44},
  [38] = {.lex_state = 44},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 44},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 44},
  [44] = {.lex_state = 44},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 43},
  [48] = {.lex_state = 43},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 43},
  [51] = {.lex_state = 43},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 43},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 43},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 43},
  [61] = {.lex_state = 43},
  [62] = {.lex_state = 43},
  [63] = {.lex_state = 43},
  [64] = {.lex_state = 43},
  [65] = {.lex_state = 43},
  [66] = {.lex_state = 43},
  [67] = {.lex_state = 43},
  [68] = {.lex_state = 43},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 43},
  [71] = {.lex_state = 43},
  [72] = {.lex_state = 43},
  [73] = {.lex_state = 43},
  [74] = {.lex_state = 43},
  [75] = {.lex_state = 43},
  [76] = {.lex_state = 43},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 43},
  [79] = {.lex_state = 43},
  [80] = {.lex_state = 43},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 43},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 43},
  [85] = {.lex_state = 43},
  [86] = {.lex_state = 43},
  [87] = {.lex_state = 43},
  [88] = {.lex_state = 43},
  [89] = {.lex_state = 43},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 43},
  [92] = {.lex_state = 43},
  [93] = {.lex_state = 43},
  [94] = {.lex_state = 43},
  [95] = {.lex_state = 43},
  [96] = {.lex_state = 43},
  [97] = {.lex_state = 43},
  [98] = {.lex_state = 43},
  [99] = {.lex_state = 43},
  [100] = {.lex_state = 43},
  [101] = {.lex_state = 43},
  [102] = {.lex_state = 43},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 43},
  [105] = {.lex_state = 43},
  [106] = {.lex_state = 43},
  [107] = {.lex_state = 43},
  [108] = {.lex_state = 43},
  [109] = {.lex_state = 43},
  [110] = {.lex_state = 43},
  [111] = {.lex_state = 43},
  [112] = {.lex_state = 43},
  [113] = {.lex_state = 43},
  [114] = {.lex_state = 43},
  [115] = {.lex_state = 43},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 43},
  [118] = {.lex_state = 43},
  [119] = {.lex_state = 43},
  [120] = {.lex_state = 43},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 43},
  [123] = {.lex_state = 43},
  [124] = {.lex_state = 43},
  [125] = {.lex_state = 43},
  [126] = {.lex_state = 43},
  [127] = {.lex_state = 43},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_syntax] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_COLON_COLON_EQ] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_rules] = ACTIONS(1),
    [anon_sym_rule] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_transition] = ACTIONS(1),
    [anon_sym_TILDE_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_PERCENTtest_COLON] = ACTIONS(1),
    [sym_regular_comment] = ACTIONS(3),
    [sym_haskell_expression] = ACTIONS(1),
    [sym_haskell_block] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(107),
    [sym_declaration] = STATE(111),
    [sym_syntax_block] = STATE(115),
    [sym_rules_block] = STATE(115),
    [sym_transition_declaration] = STATE(115),
    [sym_rewrite_rule] = STATE(115),
    [sym_test_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_syntax] = ACTIONS(7),
    [anon_sym_rules] = ACTIONS(9),
    [anon_sym_transition] = ACTIONS(11),
    [anon_sym_PERCENTtest_COLON] = ACTIONS(13),
    [sym_regular_comment] = ACTIONS(3),
    [sym_haskell_block] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(7), 1,
      anon_sym_syntax,
    ACTIONS(9), 1,
      anon_sym_rules,
    ACTIONS(11), 1,
      anon_sym_transition,
    ACTIONS(13), 1,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_haskell_block,
    STATE(111), 1,
      sym_declaration,
    STATE(3), 2,
      sym_test_comment,
      aux_sym_source_file_repeat1,
    STATE(115), 4,
      sym_syntax_block,
      sym_rules_block,
      sym_transition_declaration,
      sym_rewrite_rule,
  [38] = 11,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_syntax,
    ACTIONS(28), 1,
      anon_sym_rules,
    ACTIONS(31), 1,
      anon_sym_transition,
    ACTIONS(34), 1,
      anon_sym_PERCENTtest_COLON,
    ACTIONS(37), 1,
      sym_haskell_block,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(111), 1,
      sym_declaration,
    STATE(3), 2,
      sym_test_comment,
      aux_sym_source_file_repeat1,
    STATE(115), 4,
      sym_syntax_block,
      sym_rules_block,
      sym_transition_declaration,
      sym_rewrite_rule,
  [76] = 9,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(65), 1,
      sym_term,
    STATE(109), 1,
      sym_term_list,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [108] = 9,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      sym_primary_term,
    STATE(65), 1,
      sym_term,
    STATE(127), 1,
      sym_term_list,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [140] = 9,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      sym_primary_term,
    STATE(65), 1,
      sym_term,
    STATE(106), 1,
      sym_term_list,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [172] = 8,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      sym_primary_term,
    STATE(79), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [201] = 8,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      sym_primary_term,
    STATE(74), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [230] = 8,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      sym_primary_term,
    STATE(72), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [259] = 8,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(66), 1,
      sym_term,
    STATE(125), 1,
      sym_production_list,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [288] = 4,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
  [309] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(82), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [335] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(69), 1,
      sym_identifier,
    STATE(19), 1,
      sym_primary_term,
    STATE(43), 1,
      sym_term,
    ACTIONS(67), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(26), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [361] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(69), 1,
      sym_identifier,
    STATE(19), 1,
      sym_primary_term,
    STATE(41), 1,
      sym_term,
    ACTIONS(67), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(26), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [387] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(69), 1,
      sym_identifier,
    STATE(19), 1,
      sym_primary_term,
    STATE(38), 1,
      sym_term,
    ACTIONS(67), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(26), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [413] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(73), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
  [431] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(126), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [457] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(69), 1,
      sym_identifier,
    STATE(19), 1,
      sym_primary_term,
    STATE(37), 1,
      sym_term,
    ACTIONS(67), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(26), 2,
      sym_atom,
      sym_functor,
    STATE(44), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [483] = 6,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(79), 1,
      anon_sym_TILDE_GT,
    ACTIONS(81), 1,
      anon_sym_EQ,
    ACTIONS(83), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
    ACTIONS(77), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [507] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(87), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
  [525] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(119), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [551] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(91), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
  [569] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(93), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [595] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(86), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [621] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(84), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [647] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(95), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
  [665] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(47), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [691] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(48), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [717] = 7,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(31), 1,
      sym_primary_term,
    STATE(51), 1,
      sym_term,
    ACTIONS(47), 2,
      sym_haskell_expression,
      sym_integer_literal,
    STATE(32), 2,
      sym_atom,
      sym_functor,
    STATE(50), 3,
      sym_equality,
      sym_inequality,
      sym_transition_term,
  [743] = 3,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [760] = 5,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(99), 1,
      anon_sym_TILDE_GT,
    ACTIONS(101), 1,
      anon_sym_EQ,
    ACTIONS(103), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(75), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [780] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(93), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [794] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(71), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [808] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(85), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [822] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(89), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_TILDE_GT,
      anon_sym_EQ,
      anon_sym_SLASH_EQ,
  [836] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(23), 3,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
    ACTIONS(105), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [851] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
    ACTIONS(109), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [866] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
    ACTIONS(113), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [881] = 8,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 1,
      anon_sym_alias,
    ACTIONS(119), 1,
      sym_identifier,
    STATE(42), 1,
      aux_sym_syntax_block_repeat1,
    STATE(101), 1,
      sym_syntax_rule,
    STATE(113), 1,
      sym_type_alias,
    STATE(121), 1,
      sym_variable_list,
  [906] = 8,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      anon_sym_alias,
    ACTIONS(126), 1,
      sym_identifier,
    STATE(40), 1,
      aux_sym_syntax_block_repeat1,
    STATE(101), 1,
      sym_syntax_rule,
    STATE(113), 1,
      sym_type_alias,
    STATE(121), 1,
      sym_variable_list,
  [931] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
    ACTIONS(131), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [946] = 8,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(117), 1,
      anon_sym_alias,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      aux_sym_syntax_block_repeat1,
    STATE(101), 1,
      sym_syntax_rule,
    STATE(113), 1,
      sym_type_alias,
    STATE(121), 1,
      sym_variable_list,
  [971] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
    ACTIONS(137), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [986] = 3,
    ACTIONS(3), 1,
      sym_regular_comment,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_PERCENTtest_COLON,
      sym_haskell_block,
    ACTIONS(77), 4,
      anon_sym_syntax,
      anon_sym_rules,
      anon_sym_transition,
      sym_identifier,
  [1001] = 3,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 5,
      anon_sym_SEMI,
      anon_sym_COLON_COLON_EQ,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1015] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(143), 6,
      anon_sym_SEMI,
      anon_sym_COLON_COLON_EQ,
      anon_sym_as,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1027] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(135), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1038] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(111), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1049] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(145), 5,
      anon_sym_SEMI,
      anon_sym_COLON_COLON_EQ,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1060] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(75), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1071] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(129), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1082] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(147), 5,
      anon_sym_SEMI,
      anon_sym_COLON_COLON_EQ,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1093] = 5,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(151), 1,
      anon_sym_rule,
    STATE(54), 1,
      aux_sym_rules_block_repeat1,
    STATE(114), 1,
      sym_rule,
  [1109] = 5,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(151), 1,
      anon_sym_rule,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_rules_block_repeat1,
    STATE(114), 1,
      sym_rule,
  [1125] = 5,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    ACTIONS(157), 1,
      anon_sym_rule,
    STATE(55), 1,
      aux_sym_rules_block_repeat1,
    STATE(114), 1,
      sym_rule,
  [1141] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_type_ref_repeat1,
  [1154] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(164), 1,
      anon_sym_in,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_variable_list_repeat1,
  [1167] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(45), 1,
      sym_type_name,
    STATE(87), 1,
      sym_type_ref,
  [1180] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(170), 1,
      anon_sym_in,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_variable_list_repeat1,
  [1193] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_type_ref_repeat1,
  [1206] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_rewrite_rule_repeat1,
  [1219] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_rewrite_rule_repeat1,
  [1232] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_rewrite_rule_repeat1,
  [1245] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_rewrite_rule_repeat1,
  [1258] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(190), 1,
      anon_sym_SEMI,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    STATE(67), 1,
      aux_sym_term_list_repeat1,
  [1271] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(194), 1,
      anon_sym_SEMI,
    ACTIONS(196), 1,
      anon_sym_PIPE,
    STATE(71), 1,
      aux_sym_production_list_repeat1,
  [1284] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(190), 1,
      anon_sym_SEMI,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    STATE(73), 1,
      aux_sym_term_list_repeat1,
  [1297] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(45), 1,
      sym_type_name,
    STATE(116), 1,
      sym_type_ref,
  [1310] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_in,
    STATE(59), 1,
      aux_sym_variable_list_repeat1,
  [1323] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_type_ref_repeat1,
  [1336] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(196), 1,
      anon_sym_PIPE,
    ACTIONS(207), 1,
      anon_sym_SEMI,
    STATE(75), 1,
      aux_sym_production_list_repeat1,
  [1349] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_rewrite_rule_repeat1,
  [1362] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(211), 1,
      anon_sym_SEMI,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    STATE(73), 1,
      aux_sym_term_list_repeat1,
  [1375] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_rewrite_rule_repeat1,
  [1388] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(218), 1,
      anon_sym_SEMI,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    STATE(75), 1,
      aux_sym_production_list_repeat1,
  [1401] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(45), 1,
      sym_type_name,
    STATE(60), 1,
      sym_type_ref,
  [1414] = 3,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(223), 2,
      anon_sym_alias,
      sym_identifier,
  [1425] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(45), 1,
      sym_type_name,
    STATE(80), 1,
      sym_type_ref,
  [1438] = 4,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_rewrite_rule_repeat1,
  [1451] = 3,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(227), 1,
      anon_sym_SEMI,
    ACTIONS(229), 1,
      anon_sym_COLON_COLON_EQ,
  [1461] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(170), 2,
      anon_sym_in,
      anon_sym_COMMA,
  [1469] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(186), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1477] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(155), 2,
      anon_sym_RBRACE,
      anon_sym_rule,
  [1485] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(218), 2,
      anon_sym_SEMI,
      anon_sym_PIPE,
  [1493] = 3,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(98), 1,
      sym_type_name,
  [1503] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(214), 2,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1511] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1519] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(231), 1,
      anon_sym_SEMI,
  [1526] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(233), 1,
      anon_sym_LBRACK,
  [1533] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(235), 1,
      anon_sym_EQ_GT,
  [1540] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(237), 1,
      sym_identifier,
  [1547] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(239), 1,
      anon_sym_SEMI,
  [1554] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(241), 1,
      anon_sym_SEMI,
  [1561] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(243), 1,
      anon_sym_SEMI,
  [1568] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [1575] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(247), 1,
      anon_sym_SEMI,
  [1582] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
  [1589] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(251), 1,
      anon_sym_SEMI,
  [1596] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
  [1603] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(255), 1,
      anon_sym_LBRACK,
  [1610] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(257), 1,
      anon_sym_SEMI,
  [1617] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(259), 1,
      sym_string,
  [1624] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(261), 1,
      anon_sym_EQ_GT,
  [1631] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(263), 1,
      anon_sym_LBRACK,
  [1638] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(265), 1,
      anon_sym_SEMI,
  [1645] = 2,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    ACTIONS(45), 1,
      sym_regular_comment,
  [1652] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
  [1659] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(269), 1,
      anon_sym_SEMI,
  [1666] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(271), 1,
      anon_sym_RBRACK,
  [1673] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(273), 1,
      anon_sym_SEMI,
  [1680] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(275), 1,
      anon_sym_SEMI,
  [1687] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(277), 1,
      anon_sym_EQ,
  [1694] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(279), 1,
      anon_sym_SEMI,
  [1701] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(281), 1,
      anon_sym_SEMI,
  [1708] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(283), 1,
      anon_sym_SEMI,
  [1715] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(285), 1,
      anon_sym_as,
  [1722] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(287), 1,
      anon_sym_LBRACE,
  [1729] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(289), 1,
      sym_identifier,
  [1736] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(291), 1,
      anon_sym_SEMI,
  [1743] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(293), 1,
      anon_sym_EQ,
  [1750] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(295), 1,
      anon_sym_in,
  [1757] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(297), 1,
      anon_sym_TILDE_GT,
  [1764] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(299), 1,
      anon_sym_SEMI,
  [1771] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(301), 1,
      sym_identifier,
  [1778] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(303), 1,
      anon_sym_SEMI,
  [1785] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(305), 1,
      anon_sym_SEMI,
  [1792] = 2,
    ACTIONS(45), 1,
      sym_regular_comment,
    ACTIONS(307), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 172,
  [SMALL_STATE(8)] = 201,
  [SMALL_STATE(9)] = 230,
  [SMALL_STATE(10)] = 259,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 309,
  [SMALL_STATE(13)] = 335,
  [SMALL_STATE(14)] = 361,
  [SMALL_STATE(15)] = 387,
  [SMALL_STATE(16)] = 413,
  [SMALL_STATE(17)] = 431,
  [SMALL_STATE(18)] = 457,
  [SMALL_STATE(19)] = 483,
  [SMALL_STATE(20)] = 507,
  [SMALL_STATE(21)] = 525,
  [SMALL_STATE(22)] = 551,
  [SMALL_STATE(23)] = 569,
  [SMALL_STATE(24)] = 595,
  [SMALL_STATE(25)] = 621,
  [SMALL_STATE(26)] = 647,
  [SMALL_STATE(27)] = 665,
  [SMALL_STATE(28)] = 691,
  [SMALL_STATE(29)] = 717,
  [SMALL_STATE(30)] = 743,
  [SMALL_STATE(31)] = 760,
  [SMALL_STATE(32)] = 780,
  [SMALL_STATE(33)] = 794,
  [SMALL_STATE(34)] = 808,
  [SMALL_STATE(35)] = 822,
  [SMALL_STATE(36)] = 836,
  [SMALL_STATE(37)] = 851,
  [SMALL_STATE(38)] = 866,
  [SMALL_STATE(39)] = 881,
  [SMALL_STATE(40)] = 906,
  [SMALL_STATE(41)] = 931,
  [SMALL_STATE(42)] = 946,
  [SMALL_STATE(43)] = 971,
  [SMALL_STATE(44)] = 986,
  [SMALL_STATE(45)] = 1001,
  [SMALL_STATE(46)] = 1015,
  [SMALL_STATE(47)] = 1027,
  [SMALL_STATE(48)] = 1038,
  [SMALL_STATE(49)] = 1049,
  [SMALL_STATE(50)] = 1060,
  [SMALL_STATE(51)] = 1071,
  [SMALL_STATE(52)] = 1082,
  [SMALL_STATE(53)] = 1093,
  [SMALL_STATE(54)] = 1109,
  [SMALL_STATE(55)] = 1125,
  [SMALL_STATE(56)] = 1141,
  [SMALL_STATE(57)] = 1154,
  [SMALL_STATE(58)] = 1167,
  [SMALL_STATE(59)] = 1180,
  [SMALL_STATE(60)] = 1193,
  [SMALL_STATE(61)] = 1206,
  [SMALL_STATE(62)] = 1219,
  [SMALL_STATE(63)] = 1232,
  [SMALL_STATE(64)] = 1245,
  [SMALL_STATE(65)] = 1258,
  [SMALL_STATE(66)] = 1271,
  [SMALL_STATE(67)] = 1284,
  [SMALL_STATE(68)] = 1297,
  [SMALL_STATE(69)] = 1310,
  [SMALL_STATE(70)] = 1323,
  [SMALL_STATE(71)] = 1336,
  [SMALL_STATE(72)] = 1349,
  [SMALL_STATE(73)] = 1362,
  [SMALL_STATE(74)] = 1375,
  [SMALL_STATE(75)] = 1388,
  [SMALL_STATE(76)] = 1401,
  [SMALL_STATE(77)] = 1414,
  [SMALL_STATE(78)] = 1425,
  [SMALL_STATE(79)] = 1438,
  [SMALL_STATE(80)] = 1451,
  [SMALL_STATE(81)] = 1461,
  [SMALL_STATE(82)] = 1469,
  [SMALL_STATE(83)] = 1477,
  [SMALL_STATE(84)] = 1485,
  [SMALL_STATE(85)] = 1493,
  [SMALL_STATE(86)] = 1503,
  [SMALL_STATE(87)] = 1511,
  [SMALL_STATE(88)] = 1519,
  [SMALL_STATE(89)] = 1526,
  [SMALL_STATE(90)] = 1533,
  [SMALL_STATE(91)] = 1540,
  [SMALL_STATE(92)] = 1547,
  [SMALL_STATE(93)] = 1554,
  [SMALL_STATE(94)] = 1561,
  [SMALL_STATE(95)] = 1568,
  [SMALL_STATE(96)] = 1575,
  [SMALL_STATE(97)] = 1582,
  [SMALL_STATE(98)] = 1589,
  [SMALL_STATE(99)] = 1596,
  [SMALL_STATE(100)] = 1603,
  [SMALL_STATE(101)] = 1610,
  [SMALL_STATE(102)] = 1617,
  [SMALL_STATE(103)] = 1624,
  [SMALL_STATE(104)] = 1631,
  [SMALL_STATE(105)] = 1638,
  [SMALL_STATE(106)] = 1645,
  [SMALL_STATE(107)] = 1652,
  [SMALL_STATE(108)] = 1659,
  [SMALL_STATE(109)] = 1666,
  [SMALL_STATE(110)] = 1673,
  [SMALL_STATE(111)] = 1680,
  [SMALL_STATE(112)] = 1687,
  [SMALL_STATE(113)] = 1694,
  [SMALL_STATE(114)] = 1701,
  [SMALL_STATE(115)] = 1708,
  [SMALL_STATE(116)] = 1715,
  [SMALL_STATE(117)] = 1722,
  [SMALL_STATE(118)] = 1729,
  [SMALL_STATE(119)] = 1736,
  [SMALL_STATE(120)] = 1743,
  [SMALL_STATE(121)] = 1750,
  [SMALL_STATE(122)] = 1757,
  [SMALL_STATE(123)] = 1764,
  [SMALL_STATE(124)] = 1771,
  [SMALL_STATE(125)] = 1778,
  [SMALL_STATE(126)] = 1785,
  [SMALL_STATE(127)] = 1792,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functor, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functor, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functor, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functor, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functor, 5, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functor, 5, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_term, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_term, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_comment, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_test_comment, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inequality, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inequality, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_syntax_block_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_syntax_block_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_syntax_block_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equality, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transition_term, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transition_term, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rules_block_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rules_block_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rewrite_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rewrite_rule_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_list, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production_list, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_list, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_ref_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production_list, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_list_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_list_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_production_list_repeat1, 2, 0, 0),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_production_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_syntax_block_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_rule, 3, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_block, 4, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rules_block, 4, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_rule, 7, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rules_block, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transition_declaration, 4, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias, 4, 0, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 7, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 8, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 9, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_rule, 1, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_rule, 6, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_block, 3, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_rule, 5, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rewrite_rule, 5, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_analysislang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "analysislang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
