-- AnalysisLang related imports
import Language.AST.CodeGen.Prelude
import qualified Language.AST
import qualified Language.Range
import qualified Language.Types

-- Haskell imports
import Data.Functor.Identity


import GHC.Maybe
ast :: CodeGenProgram
ast = Language.AST.Program [Language.AST.Syntax [Language.AST.SyntaxDecl [['x'],
                                                                    ['r',
                                                                     'e',
                                                                     's',
                                                                     'u',
                                                                     'l',
                                                                     't']] "Value" [] (Language.Range.Range (Language.Range.Position 4 5 GHC.Maybe.Nothing) (Language.Range.Position 4 23 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 3 1 GHC.Maybe.Nothing) (Language.Range.Position 5 2 GHC.Maybe.Nothing)),
                      Language.AST.RulesDecl [Language.AST.RuleDecl "Simple-HaskellExpr" [] [Language.AST.Eqq (Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['V',
                                                                                                                                                                                                 'a',
                                                                                                                                                                                                 'l',
                                                                                                                                                                                                 'u',
                                                                                                                                                                                                 'e']) (Language.Range.Range (Language.Range.Position 10 7 GHC.Maybe.Nothing) (Language.Range.Position 10 14 GHC.Maybe.Nothing))) (Language.AST.HaskellExpr ['4',
                                                                                                                                                                                                                                                                                                                                                             '2'] (Language.Types.Sort ['V',
                                                                                                                                                                                                                                                                                                                                                                                        'a',
                                                                                                                                                                                                                                                                                                                                                                                        'l',
                                                                                                                                                                                                                                                                                                                                                                                        'u',
                                                                                                                                                                                                                                                                                                                                                                                        'e']) (Language.Range.Range (Language.Range.Position 10 16 GHC.Maybe.Nothing) (Language.Range.Position 10 22 GHC.Maybe.Nothing))) (Language.Types.Sort ['V',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'l',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'u',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'e']) (Language.Range.Range (Language.Range.Position 10 7 GHC.Maybe.Nothing) (Language.Range.Position 10 22 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 8 10 GHC.Maybe.Nothing) (Language.Range.Position 10 23 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 7 7 GHC.Maybe.Nothing) (Language.Range.Position 11 2 GHC.Maybe.Nothing))] [Language.AST.Comment "% This file tests HaskellExpr parsing functionality" (Language.Range.Range (Language.Range.Position 1 1 GHC.Maybe.Nothing) (Language.Range.Position 1 1 GHC.Maybe.Nothing))]