{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE LambdaCase #-}
-- AnalysisLang related imports
import Language.CodeGen.Prelude
import qualified Language.AST
import qualified Language.Range
import qualified Language.Types
import Language.Solver
import qualified Language.Solver.BacktrackingST as ST

-- Haskell imports
import Data.Functor.Identity
import qualified Data.Either
import qualified Data.Maybe
import qualified GHC.Base
import qualified Data.Map as Map
import System.Exit
import Data.List (stripPrefix)
import Data.Maybe (catMaybes)
import qualified Data.Map.Internal


import GHC.Maybe
ast :: CodeGenProgram
ast = Language.AST.Program [Language.AST.Syntax [Language.AST.SyntaxDecl [['a'],
                                                                    ['r', 'e', 's', 'u', 'l', 't'],
                                                                    ['s', 'u', 'm'],
                                                                    ['p',
                                                                     'r',
                                                                     'o',
                                                                     'd',
                                                                     'u',
                                                                     'c',
                                                                     't']] "Int" [] (Language.Range.Range (Language.Range.Position 4 5 GHC.Maybe.Nothing) (Language.Range.Position 4 35 GHC.Maybe.Nothing)),
                                           Language.AST.SyntaxDecl [['t',
                                                                     'e',
                                                                     's',
                                                                     't']] "Rules" [Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                                                                                                                'n',
                                                                                                                                                                                                't']) (Language.Range.Range (Language.Range.Position 5 25 GHC.Maybe.Nothing) (Language.Range.Position 5 31 GHC.Maybe.Nothing)),
                                                                                                              Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                                                                                                                'n',
                                                                                                                                                                                                't']) (Language.Range.Range (Language.Range.Position 5 33 GHC.Maybe.Nothing) (Language.Range.Position 5 39 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                                                                                                                      'u',
                                                                                                                                                                                                                                                                                                                                                      'l',
                                                                                                                                                                                                                                                                                                                                                      'e',
                                                                                                                                                                                                                                                                                                                                                      's']) (Language.Range.Range (Language.Range.Position 5 23 GHC.Maybe.Nothing) (Language.Range.Position 5 40 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 5 5 GHC.Maybe.Nothing) (Language.Range.Position 5 40 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 3 1 GHC.Maybe.Nothing) (Language.Range.Position 6 2 GHC.Maybe.Nothing)),
                      Language.AST.RulesDecl [Language.AST.RuleDecl "Simple-HaskellExpr" [] [Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                                                                                                                         'n',
                                                                                                                                                                                                         't']) (Language.Range.Range (Language.Range.Position 11 9 GHC.Maybe.Nothing) (Language.Range.Position 11 15 GHC.Maybe.Nothing)),
                                                                                                                       Language.AST.HaskellExpr (HaskellHatch "42" [] Data.Map.Internal.empty (\prox_0 mapping_1 -> Data.Either.Right (Language.AST.TermValue (Language.Types.IntValue 42) (Language.AST.typeAnnot prox_0 Language.Types.IntType) Language.Range.dummyRange))) (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                     'n',
                                                                                                                                                                                                                                                                                                                                                                                                     't']) (Language.Range.Range (Language.Range.Position 11 17 GHC.Maybe.Nothing) (Language.Range.Position 11 22 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'u',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'l',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             's']) (Language.Range.Range (Language.Range.Position 11 7 GHC.Maybe.Nothing) (Language.Range.Position 11 24 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 9 10 GHC.Maybe.Nothing) (Language.Range.Position 11 25 GHC.Maybe.Nothing)),
                                              Language.AST.RuleDecl "Arithmetic-HaskellExpr" [] [Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                                                                                                                             'n',
                                                                                                                                                                                                             't']) (Language.Range.Range (Language.Range.Position 15 9 GHC.Maybe.Nothing) (Language.Range.Position 15 15 GHC.Maybe.Nothing)),
                                                                                                                           Language.AST.HaskellExpr (HaskellHatch "10 + 5" [['+']] Data.Map.Internal.empty (\prox_2 mapping_3 -> Data.Either.Right (Language.AST.TermValue (Language.Types.IntValue (10 + 5)) (Language.AST.typeAnnot prox_2 Language.Types.IntType) Language.Range.dummyRange))) (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                                        'n',
                                                                                                                                                                                                                                                                                                                                                                                                                        't']) (Language.Range.Range (Language.Range.Position 15 17 GHC.Maybe.Nothing) (Language.Range.Position 15 26 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'u',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'l',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                's']) (Language.Range.Range (Language.Range.Position 15 7 GHC.Maybe.Nothing) (Language.Range.Position 15 28 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 13 10 GHC.Maybe.Nothing) (Language.Range.Position 15 29 GHC.Maybe.Nothing)),
                                              Language.AST.RuleDecl "Var-Access" [Language.AST.Eqq (Language.AST.Atom (Data.Functor.Identity.Identity "a") (Language.Types.Sort ['I',
                                                                                                                                                                                 'n',
                                                                                                                                                                                 't']) (Language.Range.Range (Language.Range.Position 24 7 GHC.Maybe.Nothing) (Language.Range.Position 24 9 GHC.Maybe.Nothing))) (Language.AST.TermValue (Language.Types.IntValue 5) Language.Types.IntType (Language.Range.Range (Language.Range.Position 24 11 GHC.Maybe.Nothing) (Language.Range.Position 24 13 GHC.Maybe.Nothing))) (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              't']) (Language.Range.Range (Language.Range.Position 24 7 GHC.Maybe.Nothing) (Language.Range.Position 24 13 GHC.Maybe.Nothing)),
                                                                                  Language.AST.Eqq (Language.AST.Atom (Data.Functor.Identity.Identity "product") (Language.Types.Sort ['I',
                                                                                                                                                                                       'n',
                                                                                                                                                                                       't']) (Language.Range.Range (Language.Range.Position 24 15 GHC.Maybe.Nothing) (Language.Range.Position 24 23 GHC.Maybe.Nothing))) (Language.AST.HaskellExpr (HaskellHatch "a * 2" [['*'],
                                                                                                                                                                                                                                                                                                                                                                          ['a']] Data.Map.Internal.empty (\prox_4 mapping_5 -> Data.Maybe.maybe (Data.Either.Left GHC.Base.$ (UserError GHC.Base.$ ("Variable " GHC.Base.++ ("a" GHC.Base.++ " not found")))) (\case
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {Language.AST.TermValue value_6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       _
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       _ -> Data.Maybe.maybe (Data.Either.Left GHC.Base.$ InvalidTypePassed Language.Types.IntType (Language.Types.typeOf value_6)) Data.Either.Right (Language.Types.asType Language.Types.SIntType value_6);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _ -> Data.Either.Left GHC.Base.$ (UserError GHC.Base.$ ("Expected TermValue for variable " GHC.Base.++ "a"))}) (Data.Map.Internal.lookup "a" mapping_5) GHC.Base.>>= (\a -> Data.Either.Right (Language.AST.TermValue (Language.Types.IntValue (a * 2)) (Language.AST.typeAnnot prox_4 Language.Types.IntType) Language.Range.dummyRange)))) (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   't']) (Language.Range.Range (Language.Range.Position 24 25 GHC.Maybe.Nothing) (Language.Range.Position 24 34 GHC.Maybe.Nothing))) (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           't']) (Language.Range.Range (Language.Range.Position 24 15 GHC.Maybe.Nothing) (Language.Range.Position 24 34 GHC.Maybe.Nothing))] [Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          't']) (Language.Range.Range (Language.Range.Position 25 9 GHC.Maybe.Nothing) (Language.Range.Position 25 15 GHC.Maybe.Nothing)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Language.AST.Atom (Data.Functor.Identity.Identity "product") (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           't']) (Language.Range.Range (Language.Range.Position 25 17 GHC.Maybe.Nothing) (Language.Range.Position 25 24 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'u',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'l',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   's']) (Language.Range.Range (Language.Range.Position 25 7 GHC.Maybe.Nothing) (Language.Range.Position 25 26 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 23 10 GHC.Maybe.Nothing) (Language.Range.Position 25 27 GHC.Maybe.Nothing)),
                                              Language.AST.RuleDecl "Complex-Arithmetic" [] [Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                                                                                                                         'n',
                                                                                                                                                                                                         't']) (Language.Range.Range (Language.Range.Position 29 9 GHC.Maybe.Nothing) (Language.Range.Position 29 15 GHC.Maybe.Nothing)),
                                                                                                                       Language.AST.HaskellExpr (HaskellHatch "6 * 7 + 2" [['*'],
                                                                                                                                                                           ['+']] Data.Map.Internal.empty (\prox_7 mapping_8 -> Data.Either.Right (Language.AST.TermValue (Language.Types.IntValue (6 * 7 + 2)) (Language.AST.typeAnnot prox_7 Language.Types.IntType) Language.Range.dummyRange))) (Language.Types.Sort ['I',
                                                                                                                                                                                                                                                                                                                                                                                                                          'n',
                                                                                                                                                                                                                                                                                                                                                                                                                          't']) (Language.Range.Range (Language.Range.Position 29 17 GHC.Maybe.Nothing) (Language.Range.Position 29 29 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'u',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'l',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  's']) (Language.Range.Range (Language.Range.Position 29 7 GHC.Maybe.Nothing) (Language.Range.Position 29 31 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 27 10 GHC.Maybe.Nothing) (Language.Range.Position 29 32 GHC.Maybe.Nothing))] (Language.Range.Range (Language.Range.Position 8 7 GHC.Maybe.Nothing) (Language.Range.Position 30 2 GHC.Maybe.Nothing))] [Language.AST.Comment "% This file tests HaskellExpr parsing and execution functionality" (Language.Range.Range (Language.Range.Position 1 1 GHC.Maybe.Nothing) (Language.Range.Position 1 1 GHC.Maybe.Nothing)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Language.AST.Comment "% Test queries to verify Haskell expressions execute correctly" (Language.Range.Range (Language.Range.Position 32 1 GHC.Maybe.Nothing) (Language.Range.Position 32 1 GHC.Maybe.Nothing)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Language.AST.Comment "codegen_test: t(result, 42)" (Language.Range.Range (Language.Range.Position 33 1 GHC.Maybe.Nothing) (Language.Range.Position 33 1 GHC.Maybe.Nothing)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Language.AST.Comment "codegen_test: t(sum , 15)" (Language.Range.Range (Language.Range.Position 34 1 GHC.Maybe.Nothing) (Language.Range.Position 34 1 GHC.Maybe.Nothing)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Language.AST.Comment "codegen_test: t(product, 44)" (Language.Range.Range (Language.Range.Position 35 1 GHC.Maybe.Nothing) (Language.Range.Position 35 1 GHC.Maybe.Nothing)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Language.AST.Comment "codegen_test: t(result, 10)" (Language.Range.Range (Language.Range.Position 36 1 GHC.Maybe.Nothing) (Language.Range.Position 36 1 GHC.Maybe.Nothing))]

-- Test queries parsed and type checked during code generation
testQueries :: [PureTerm' CodeGenPhase]
testQueries = [Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                             'n',
                                                                                                             't']) (Language.Range.Range (Language.Range.Position 1 3 GHC.Maybe.Nothing) (Language.Range.Position 1 9 GHC.Maybe.Nothing)),
                           Language.AST.TermValue (Language.Types.IntValue 42) Language.Types.IntType (Language.Range.Range (Language.Range.Position 1 11 GHC.Maybe.Nothing) (Language.Range.Position 1 13 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                      'u',
                                                                                                                                                                                                                                                      'l',
                                                                                                                                                                                                                                                      'e',
                                                                                                                                                                                                                                                      's']) (Language.Range.Range (Language.Range.Position 1 1 GHC.Maybe.Nothing) (Language.Range.Position 1 13 GHC.Maybe.Nothing)),
 Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "sum") (Language.Types.Sort ['I',
                                                                                                          'n',
                                                                                                          't']) (Language.Range.Range (Language.Range.Position 1 3 GHC.Maybe.Nothing) (Language.Range.Position 1 7 GHC.Maybe.Nothing)),
                           Language.AST.TermValue (Language.Types.IntValue 15) Language.Types.IntType (Language.Range.Range (Language.Range.Position 1 9 GHC.Maybe.Nothing) (Language.Range.Position 1 11 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                     'u',
                                                                                                                                                                                                                                                     'l',
                                                                                                                                                                                                                                                     'e',
                                                                                                                                                                                                                                                     's']) (Language.Range.Range (Language.Range.Position 1 1 GHC.Maybe.Nothing) (Language.Range.Position 1 11 GHC.Maybe.Nothing)),
 Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "product") (Language.Types.Sort ['I',
                                                                                                              'n',
                                                                                                              't']) (Language.Range.Range (Language.Range.Position 1 3 GHC.Maybe.Nothing) (Language.Range.Position 1 10 GHC.Maybe.Nothing)),
                           Language.AST.TermValue (Language.Types.IntValue 44) Language.Types.IntType (Language.Range.Range (Language.Range.Position 1 12 GHC.Maybe.Nothing) (Language.Range.Position 1 14 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                      'u',
                                                                                                                                                                                                                                                      'l',
                                                                                                                                                                                                                                                      'e',
                                                                                                                                                                                                                                                      's']) (Language.Range.Range (Language.Range.Position 1 1 GHC.Maybe.Nothing) (Language.Range.Position 1 14 GHC.Maybe.Nothing)),
 Language.AST.Functor "t" [Language.AST.Atom (Data.Functor.Identity.Identity "result") (Language.Types.Sort ['I',
                                                                                                             'n',
                                                                                                             't']) (Language.Range.Range (Language.Range.Position 1 3 GHC.Maybe.Nothing) (Language.Range.Position 1 9 GHC.Maybe.Nothing)),
                           Language.AST.TermValue (Language.Types.IntValue 10) Language.Types.IntType (Language.Range.Range (Language.Range.Position 1 11 GHC.Maybe.Nothing) (Language.Range.Position 1 13 GHC.Maybe.Nothing))] (Language.Types.Sort ['R',
                                                                                                                                                                                                                                                      'u',
                                                                                                                                                                                                                                                      'l',
                                                                                                                                                                                                                                                      'e',
                                                                                                                                                                                                                                                      's']) (Language.Range.Range (Language.Range.Position 1 1 GHC.Maybe.Nothing) (Language.Range.Position 1 13 GHC.Maybe.Nothing))]

main :: IO ()
main = do
  putStrLn $ "Running " ++ show (length testQueries) ++ " test queries..."
  results <- mapM runTestQuery (zip [1..] testQueries)
  let passed = length $ filter id results
      total = length results
      failed = total - passed
  
  putStrLn $ "Results: " ++ show passed ++ "/" ++ show total ++ " passed"
  
  if failed == 0
    then do
      putStrLn "All tests passed!"
      exitWith ExitSuccess
    else do
      putStrLn $ show failed ++ " tests failed"
      exitWith (ExitFailure 1)

runTestQuery :: (Int, PureTerm' CodeGenPhase) -> IO Bool
runTestQuery (idx, query) = do
  putStr $ "Testing query " ++ show idx ++ ": " ++ show query ++ " ... "
  let Program decls _ = ast
  let rules = [rule | RulesDecl rules _ <- decls, rule <- rules]
  let engineCtx = fromRules @[] rules
  let solverComputation = ST.runST $ runSolver engineCtx (solve @CodeGenPhase @[] query)
  
  case solverComputation of
    [] -> do
      putStrLn "FAIL (no solutions)"
      return False
    _ -> do
      putStrLn "PASS"
      return True